### ISSUE TITLE
How to build and pack the app for production

### ISSUE THREAD

**Issue by gurvancampion** [caoxiemeihao/nuxt-electron#1]
Hello,
First thanks for making this plugin! I'm using it to make a sample project with trpc and prisma.
So far I have no problem running it in development however after hours trying to figure out I can't make it work after I build and package the App. I can load my `index.html`:
<img width="604" alt="CleanShot 2022-12-04 at 20 43 42@2x" src="https://user-images.githubusercontent.com/32047986/205511926-f1c95e81-a724-46fc-9038-a61cc9750059.png">
But the other files cannot be found, the path is not correct as it doesn't point to the electron app.asar:
<img width="561" alt="CleanShot 2022-12-04 at 20 45 53@2x" src="https://user-images.githubusercontent.com/32047986/205511983-5917ae6c-9cee-41f0-ac7f-7a86d37d20a3.png">

Here is a reproduction: https://github.com/gurvan-guss/nuxt-electron-trpc-prisma

Did you manage to build and run an App with Nuxt 3? or do you have any clue of what I'm doing wrong?

Thanks

**Comment by zavodnyrichard** [comment]
You have to set NUXT_APP_BASE_URL enviroment variable in .env file at the root of your project to this:

`NUXT_APP_BASE_URL: ./`

Details are also in this thread: #https://github.com/nuxt/framework/discussions/4569#discussioncomment-4340667

**Comment by caoxiemeihao** [comment]
Or use the following configuration, which will be integrated by default in the next version of `nuxt-plugin-electron`.
```diff
const nuxtConfig = defineNuxtConfig({
+ app: {
+   baseURL: './',
+ },
  ssr: false,
  vite: {
    server: {
      middlewareMode: false,
    },
  },
  modules: [
    async (options, nuxt) => {
      // @ts-expect-error: remove ts error
      nuxt.hooks.hook('vite:extendConfig', config => config.plugins.push(
        vuetify(),
      ))
    },
  ],
  build: {
    transpile: ['vuetify'],
  },
})

export default withElectron({
  include: ['electron', 'server'],
})(nuxtConfig)
```

**Comment by caoxiemeihao** [comment]
`nuxt-plugin-electron@0.1.1` is out！

**Comment by caoxiemeihao** [comment]
👋 I'm sorry to say.
`nuxt-plugin-electron` has deprecated, you can use `nuxt-electron` instead it.
https://github.com/caoxiemeihao/nuxt-electron/blob/40956d3ab6360ba3197f2aaf1fe838a4cc649a2f/examples/quick-start/nuxt.config.ts#L1-L9

My previous understanding of Nuxt was wrong. In Nuxt we should be using `modules` not `plugin`.
So I rewrote a `nuxt-electron`, which looks more appropriate in Nuxt.
