### ISSUE TITLE
How to access contextBridge in Nuxt

### ISSUE THREAD

**Issue by redmondking** [caoxiemeihao/nuxt-electron#11]
Hello,

I have been using this but have been unable to access my preload commands in the app. Using window.myAPI.myfunction throws an error of undefined.

How do I resolve this? Does there need to be an additional import for it to work. See example code below.

preload.ts:
```
const {contextBridge, app} = require('electron')

const windowAPI = {
    closeWindow: () => app.quit
}

contextBridge.exposeInMainWorld("api", windowAPI);
```

index.vue: 
```
<script setup lang='ts'>
const isFullscreen = ref(false)
const test = () => {
    isFullscreen.value = !isFullscreen.value
}

const quitApp = window.api.closeWindow()

</script>
```

**Comment by caoxiemeihao** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/26263658/220496853-955d80ed-fc11-42e6-b285-ba32ce9244f6.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/26263658/220496924-81df6690-041f-4892-a0b5-8fa17817ec8f.png">
