### ISSUE TITLE
How to set custom App location for development?

### ISSUE THREAD

**Issue by mtdvlpr** [caoxiemeihao/nuxt-electron#13]
I want to have a separate local app location ([`app.getPath('userData')`](https://electronjs.org/docs/api/app#appgetpathname)) for development vs production. Right now, both are stored under the package.json name property. I want for example the production app to be stored in `package-name` and the development app to be stored in `Electron` or `package-name-dev`. The benefit is that the different config files don't get mixed and you can have a production app on your device along with the development app. Is that possible?

**Comment by caoxiemeihao** [comment]
I'm not sure where you hung up and I don't think the problem you encountered is a real one
At any time you can distinguish between production or development environments with `process.env.VITE_DEV_SERVER_URL`, which can be used to determine whether to read `package-name.json` or `package-name-dev.json`

```ts
  if (process.env.VITE_DEV_SERVER_URL) {
    // development
  } else {
    // production
  }
```

**Comment by mtdvlpr** [comment]
The problem is not while the app is running, but before. I want to be able to configure the app to "live" somewhere else, instead of the default path (which is automatically determined based on package name). How do I manually tell Electron to place the app (along with all the installation files) in a different folder?

**Comment by mtdvlpr** [comment]
I think I found my answer [here]. Thanks anyway!
