### ISSUE TITLE
[ERROR] TypeError: Error processing argument at 0, conversion failure from undefined

### ISSUE THREAD

**Issue by angelhdzmultimedia** [caoxiemeihao/nuxt-electron#17]
The app runs beautifully in dev mode.

But in build mode, it throws that error in the terminal and the electron window is empty.

`[ERROR] TypeError: Error processing argument at 0, conversion failure from undefined`

This is my package.json:
![image](https://user-images.githubusercontent.com/10191085/225510156-d17f381a-f9ee-4e30-8ecd-961586cb9cd7.png)

I tried using the version in the template. Didn't work. So I used `pnpm update` to update all the packages to latest.

I have an idea what this can be! The error mentions something about an argument, 
so the only function I see that is being passed an argument that can be undefined is the `loadURL(process.env.VITE_DEV_SERVER_URL!)` in `electron/main.ts`.

But I don't see anything in the examples that I have to configure Vite or something.

Hope someone kindly will point me in the right direction, thank you!

**Comment by angelhdzmultimedia** [comment]
Just in case:
![image](https://user-images.githubusercontent.com/10191085/225511861-d9f1c06e-fb58-4e5e-a2ef-5e45c0754849.png)

![image](https://user-images.githubusercontent.com/10191085/225511957-e95bd61b-b0e5-479e-a40c-f7713f59a062.png)

**Comment by mtdvlpr** [comment]
`process.env.VITE_DEV_SERVER_URL` is undefined in production. You should use `process.env.VITE_PUBLIC` for production.

See https://github.com/caoxiemeihao/nuxt-electron/blob/main/examples/quick-start/electron/main.ts

**Comment by angelhdzmultimedia** [comment]
> `process.env.VITE_DEV_SERVER_URL` is undefined in production. You should use `process.env.VITE_PUBLIC` for production.
> 
> See https://github.com/caoxiemeihao/nuxt-electron/blob/v0.4.2/examples/quick-start/electron/main.ts#L31-L36

Working beautifully! I'm been exploring Vue/Vite heavily only in development mode. This is the first time building. Missed that, appreciate it a lot!

Wishing you all health, peace, and success! 🔥☕🤝
