### ISSUE TITLE
when run app in nuxt build && electron-builder, app just white no error

### ISSUE THREAD

**Issue by fikrihanda** [caoxiemeihao/nuxt-electron#32]
Hi.

im just try using nuxt electron, i got problem with build, when run nuxi dev is fine but run in nuxi build && electron-builder, app just white no error log or something, maybe my config is wrong or something ? but my config is follow in example quick-start

![image](https://user-images.githubusercontent.com/37224559/236772381-e19c92f3-d069-4110-823a-d57035e20cc4.png)

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?

**Comment by fikrihanda** [comment]
sorry my bad im missing some code in main
