### ISSUE TITLE
White page after app is installed

### ISSUE THREAD

**Issue by bbaltatu** [caoxiemeihao/nuxt-electron#36]
Hi,
I am using your module and when I am running "npm run dev" everything is ok and I see the app in an electron window. After I build the app and install it, it is open but I have a white window. 
Can you tell me why I don't see the app?

Additional info:
VITE_DEV_SERVER_URL may have a wrong value ( I tried with HTTP://localhost:3000 but).

OS: Ventura 13.4
CPU: M2

**Comment by caoxiemeihao** [comment]
You can try use the quick-start
https://github.com/caoxiemeihao/nuxt-electron/tree/main/examples%2Fquick-start

**Comment by bbaltatu** [comment]
Thank you. In the quick start I don't have any issue. 
I didn't use it from the beginning because NPM don't like "workspace
