### ISSUE TITLE
Trouble with vuetify

### ISSUE THREAD

**Issue by cenoroid** [caoxiemeihao/nuxt-electron#4]
Hey, I can use vuetify fine when I am running yarn dev, however when I build the app vuetify isn't there anymore, I've tried to figure it out for hours with no success, but it seems to me that plugins are not included somehow in the build. Let me know if you need me to upload my repo. Any help will be greatly appreciated!

Build: 
![image](https://user-images.githubusercontent.com/81117999/209409007-27235b73-8623-415e-bea3-5a424211ed6c.png)
Dev: 
![image](https://user-images.githubusercontent.com/81117999/209409028-6dce91cb-a656-41c1-a7e5-1dfff27d8cee.png)
nuxt.config.js
![image](https://user-images.githubusercontent.com/81117999/209409065-1b00fa24-7f1e-4120-ae7e-79a6d4d60ff3.png)
src/plugins/vuetify.ts
![image](https://user-images.githubusercontent.com/81117999/209409094-251a088f-259c-4a38-8adb-ee26bd175290.png)

**Comment by caoxiemeihao** [comment]
Can you provide a minimal repo?

**Comment by cenoroid** [comment]
https://gitlab.com/nikosdendrinos/electron-nuxt3-vuetify
it seems like none of the css is included in the build
- yarn install
- yarn dev
creates properly built app
- yarn build
creates app with issues

**Comment by cenoroid** [comment]
I think this the problem 
![image](https://user-images.githubusercontent.com/81117999/209483682-c484d048-c63b-47f9-ac05-82f4e16e1708.png)

**Comment by caoxiemeihao** [comment]
Please update the latest version of `nuxt-electron`.
