### ISSUE TITLE
How do I use this project with a preload script?

### ISSUE THREAD

**Issue by itsrachelfish** [caoxiemeihao/nuxt-electron#41]
I am trying to use IPC to communicate between my main electron process and the render process. https://www.electronjs.org/docs/latest/tutorial/ipc

I cannot find any documentation about how to use a preload script with `nuxt-electron`. Any help would be appreciated

**Comment by caoxiemeihao** [comment]
Hey! Maybe the quick-start is better for you.

https://github.com/caoxiemeihao/nuxt-electron/blob/v0.6.0/examples/quick-start/nuxt.config.ts#L10-L15

<img width="900" alt="image" src="https://github.com/caoxiemeihao/nuxt-electron/assets/26263658/27ce9b64-fb92-4493-86b1-51e548a515af">
