### ISSUE TITLE
Build Not Including Tailwindcss

### ISSUE THREAD

**Issue by Patrity** [caoxiemeihao/nuxt-electron#43]
There may be a procedure necessary for including tailwind files into the build, however, currently it appears when using TailwindCSS and Nuxt-electron, the tailwind files are not built.
When using the dev command, tailwind styling does render, it is only when serving the built project.

**To Reproduce:**
I have created a bare basic project to demonstrate: https://github.com/Patrity/electron-nuxt-example
In this project, I first created a blank nuxt 3 project, then added tailwind css.
I built the project then served it with node to verify that tailwind css was rendered properly.
I then followed the setup instructions here: https://github.com/caoxiemeihao/nuxt-electron
and also included the main.ts from the example project here: https://github.com/caoxiemeihao/nuxt-electron/blob/main/examples/quick-start/electron/main.ts

Expected result:
![image](https://github.com/caoxiemeihao/nuxt-electron/assets/42813882/512a1b40-9ddc-49ac-8417-2753cc33fe77)

Built result:
![image](https://github.com/caoxiemeihao/nuxt-electron/assets/42813882/840d5fbf-23c7-4097-b985-a13749047226)

**Comment by Patrity** [comment]
I believe the issue is solved by setting ssr to false. I verified it on the demo project, but also a larger project I am working with.
I submitted a PR to add this step to the setup process.
https://github.com/caoxiemeihao/nuxt-electron/pull/44

I noticed that there is a note stating that SPA mode will be enabled, but it either is not working properly or ssr still needs to be manually set.

**Comment by vuthanhbayit** [comment]
> I believe the issue is solved by setting ssr to false. I verified it on the demo project, but also a larger project I am working with. I submitted a PR to add this step to the setup process. #44
> 
> I noticed that there is a note stating that SPA mode will be enabled, but it either is not working properly or ssr still needs to be manually set.

Thanks for saving my work day
