### ISSUE TITLE
Nuxt is not ready yet when electron start

### ISSUE THREAD

**Issue by YunYouJun** [caoxiemeihao/nuxt-electron#47]
![image](https://github.com/caoxiemeihao/nuxt-electron/assets/25154432/10d1dcdf-1605-4892-80ad-6eb1e707ad5d)

## Reproduction

- clone [vitesse-nuxt-electron](https://github.com/YunLeFun/vitesse-nuxt-electron)
- `pnpm dev`

When nuxt has many dependencies and starts slowly, we can see `nuxt is not ready yet`.

Refresh after a few seconds to restore normal.

**Comment by caoxiemeihao** [comment]
**TODO**

- [ ] enhance DX.

**Comment by OndraRehounek** [comment]
this issue stopped happening to us when we upgraded to Nuxt 3.6 (3.6.5)
