### ISSUE TITLE
The Nuxt 3 Devtools are stuck at "connecting to the server"

### ISSUE THREAD

**Issue by DerSimeon** [caoxiemeihao/nuxt-electron#51]
The title says it, there isn't much to add.

**Comment by caoxiemeihao** [comment]
I guess you used something in the Renderer process that caused this problem. Can you provide a reproduction repo?

**Comment by caoxiemeihao** [comment]
I downgraded `nuxt` to `3.6.5` and everything works fine. You can try using the latest **quick-start**.
