### ISSUE TITLE
How to generate source map to debug main.ts

### ISSUE THREAD

**Issue by OndraRehounek** [caoxiemeihao/nuxt-electron#52]
Hi, 

we are trying to make JetBrains (or Visual Studio Code) node.js debuggers working with main.ts - is there any option to enable source map to generated main.js file so we can add breakpoints to original TS files?

Of course we tried to enable it in project tsconfig.json but that did not change anything.

Thank you for your time.

**Comment by HMaker** [comment]
You can pass additional settings to the Vite bundler in the `nuxt-electron` module settings:
```ts
export default defineNuxtConfig({
  modules: ['nuxt-electron'],
  electron: {
    build: [
      {
        // Main-Process entry file of the Electron App.
        entry: 'electron/main.ts',
        vite: {
          build: {
            sourcemap: true
          }
        }
      },
    ],
  },
})
```

**Comment by HMaker** [comment]
@OndraRehounek how you configured VSCode debugger to properly launch Nuxt with electron?
