### ISSUE TITLE
Nuxt 3.8.0 bugs

### ISSUE THREAD

**Issue by abarke** [caoxiemeihao/nuxt-electron#53]
Not sure if this is due to Nuxt directly or if something needs to be fixed in `nuxt-electron`.

After installing Nuxt v3.8.0, `pnpm dev` fails with errors like: `defineNuxtPlugin` not defined in `main.js`

These plugins should not even be included in the build. Somehow it worked in Nuxt v3.7.4.

I eventually solved it as in `main.ts` I was using a type from one of the plugins, however the build loaded everything into the build which made it fail. Once I fixed it, I then ran into another error which did not load the app at all and the screen blinked with this error which was not visible in the console 🙃 (see below). Which at that point I reverted to Nuxt 3.7.4.

![image](https://github.com/caoxiemeihao/nuxt-electron/assets/34715541/f7088ab0-c5e6-41cf-ae7f-f3ba93655120)

**Comment by amplitudesxd** [comment]
It's an upstream issue, wait for nuxt v3.8.1, or disable appManifest.
https://github.com/nuxt/nuxt/issues/23831

**Comment by danielcmm** [comment]
Error still occurs in 3.8.2. As far as i can tell, happens when there is a 'public' section declared inside runtimeConfig.
