### ISSUE TITLE
nuxt@^3.8.0 set baseURL is invalid

### ISSUE THREAD

**Issue by okxiaoliang4** [caoxiemeihao/nuxt-electron#59]
downgrade to nuxt@^3.7.0 works fine

**Comment by OlaAlsaker** [comment]
I have made a PR for this issue:
https://github.com/caoxiemeihao/nuxt-electron/pull/60

Meanwhile, the solution will be to add this to your `nuxt.config.ts`:

```ts
nitro: {
  runtimeConfig: {
    app: {
      baseURL: './',
    }
  }
}
```
