### ISSUE TITLE
Nuxt Devtools 1.0.6 problem with nuxt-electron 0.6.0 & 0.7.0

### ISSUE THREAD

**Issue by RichySano** [caoxiemeihao/nuxt-electron#63]
Hi @caoxiemeihao,

I don't know if I'm doing the right thing by opening an issue here or on @nuxt/devtools repository but I have a problem.

If I use @nuxt/devtools@1.0.2 with nuxt-electron@0.6.0 I have no problem.

![image](https://github.com/caoxiemeihao/nuxt-electron/assets/89872071/de9944f5-6717-4037-9409-c1a42412f120)

If I use @nuxt/devtools@1.0.6 with nuxt-electron@0.6.0, I have this problem.

![image](https://github.com/caoxiemeihao/nuxt-electron/assets/89872071/3a97bb0d-567d-4ffc-8b50-0eaf8debcec5)

I've added

nitro: {
    runtimeConfig: {
      app: {
        baseURL: './',
      }
    }    
  },

in nuxt.config.ts file.

And if i use @nuxt/devtools@1.0.6 with nuxt-electron@0.7.0, I have this problem.

![image](https://github.com/caoxiemeihao/nuxt-electron/assets/89872071/999cdf99-a77a-4e2b-bf47-882ccf0407f6)

listSerialPorts is in preload.ts file of folder electron.

and i've commented

nitro: {
    runtimeConfig: {
      app: {
        baseURL: './',
      }
    }    
  },

if not, I have the same problem as with version nuxt-electron@0.6.0.

The problem seems to start from version 1.0.3 of @nuxt/devtools.

Another thing, do you know why I get this error if I use import { SerialPort } from 'serialport' instead of const { SerialPort } = require('serialport') ?

![image](https://github.com/caoxiemeihao/nuxt-electron/assets/89872071/e2ab23ca-78fb-4940-aec6-a00dadbb15d3)

Here the link for test repository.

https://github.com/RichySano/nuxt-electron-app.git

Thank you in advance for your assistance and for your project. Excellent work

**Comment by caoxiemeihao** [comment]
Hey! 👋
You can try the following changes. I explain it here 👉 https://github.com/caoxiemeihao/nuxt-electron/issues/74

**package.json**

```diff
{
  "scripts": {
-   "dev": "nuxt dev"
+   "dev": "nuxt dev--no-fork"
  }
}
```

**Comment by RichySano** [comment]
My answer is a little late but thank you very much
