### ISSUE TITLE
I am getting error while using quick-start example

### ISSUE THREAD

**Issue by abhisina** [caoxiemeihao/nuxt-electron#70]
> 50 verbose cwd /home/user/nuxt-electron/examples/quick-start
> 51 verbose Linux xxx
> 52 verbose node v21.7.1
> 53 verbose npm  v10.5.0
> 54 error code EUNSUPPORTEDPROTOCOL
> 55 error Unsupported URL Type "workspace:": workspace:*
> 56 verbose exit 1

getting above error when I do `npm install`  from quick-start directory
I understand that this might be very basic but I am just starting, please help me out

**Comment by JulienChampagnol** [comment]
Replace "nuxt-electron": "workspace:*" by "nuxt-electron": "0.7.0" in package.json and re-run npm install, this worked for me

**Comment by abhisina** [comment]
@JulienChampagnol many thanks, closing this
