### ISSUE TITLE
VITE_DEV_SERVER_URL is a random port

### ISSUE THREAD

**Issue by abarke** [caoxiemeihao/nuxt-electron#77]
Since upgrading electron, nuxt and nuxt-electron, electron does not respect the line anymore:

Previously this worked. But now electron ignores this and uses `VITE_DEV_SERVER_URL`
```ts
win.loadURL("http://localhost:3000");
```

`VITE_DEV_SERVER_URL` is always set to a random port

I seem to remember that some time ago it was always port 3000. 
I need to explicity set it to 3000 as I want to persist localstorage and user session.

How can I fix this so electron in dev/prod mode always used port 3000?

**Comment by abarke** [comment]
When starting nuxt it even says it's opening on 3000:

<img width="406" alt="image" src="https://github.com/caoxiemeihao/nuxt-electron/assets/34715541/2209f90f-f18d-4db7-a514-0b7ce5009ac1">

But `VITE_DEV_SERVER_URL=http://localhost:51622`  🤔

All very confusing 😵‍💫

**Comment by abarke** [comment]
This one is definitely strange. When I change the `electron/main.ts` it rebuilds but does not update in `electron-dist` 🤔 if I remove the existing `main.js`, electron fail to run with `Unable to find electron app`.

OK... now I found the issue. I stupidly missed a dependency upgrade regression/migration issue import error in the electron logs, so it failed to build the `main.js` file. Electron however would still open as the `preload.ts` was there and an old version of the `main.js` giving the illusion of caching. 

Now I fixed the error and `main.js` is building again, normality is restored and I'm a happy chappy 🙂 what a ride 🚵

**Comment by kingyue737** [comment]
In Nuxt we should not read from `VITE_DEV_SERVER_URL` which is set by this module. As you've seen, it's a random port.

https://github.com/caoxiemeihao/nuxt-electron/blob/d7cf10ddaf8e050564d46b0a906cc7a468573e60/src/index.ts#L110

I think the following is the right URL for window to load:
```ts
win.loadURL(JSON.parse(process.env.__NUXT_DEV__!).proxy.url)
```

**Comment by hifron** [comment]
According electron tutorial ESM modules support [could vary](https://www.electronjs.org/docs/latest/tutorial/esm#renderer-process) according required build.

Recommended is to client builds of [vite](https://electron-vite.org/guide/features) so nuxt should support client side rendering and build without ssr and maybe expose some ipc isolations and sandbox [webpreferences](https://www.electronjs.org/docs/latest/tutorial/security).

**Comment by hifron** [comment]
https://nuxt.com/docs/api/nuxt-config#loaders
https://nitro.build/guide
https://nitro.build/config#devproxy
serveStatic
