### ISSUE TITLE
Respect module best practices

### ISSUE THREAD

**Issue by Atinux** [caoxiemeihao/nuxt-electron#9]
Could you check how is define the module starter on https://github.com/nuxt/starter/tree/module ?

Ex: https://github.com/caoxiemeihao/nuxt-electron/blob/07c9971adadec0927c605523ee1b142c2079ffef/package.json#L7-L12 vs https://github.com/nuxt/starter/blob/364444f60e099296051bf49ff292c414ab9dde55/package.json#L7-L13

**Comment by caoxiemeihao** [comment]
abf84f8 fix it :)
